version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploaded_files:/app/uploaded_files
    depends_on:
      - db
      - redis
      - jaeger
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/insight_miner
      REDIS_URL: redis://redis:6379/0
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-credentials.json # Placeholder
      AWS_ACCESS_KEY_ID: your_aws_access_key_id # Placeholder
      AWS_SECRET_ACCESS_KEY: your_aws_secret_access_key # Placeholder
      AWS_REGION_NAME: us-east-1 # Placeholder
      EMAIL_USERNAME: your_email@example.com # Placeholder
      EMAIL_PASSWORD: your_email_password # Placeholder
      EMAIL_SERVER: smtp.example.com # Placeholder
      EMAIL_PORT: 587 # Placeholder
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: insight_miner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./backend/uploaded_files:/app/uploaded_files
    depends_on:
      - redis
      - db
      - jaeger
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/insight_miner
      REDIS_URL: redis://redis:6379/0
      EMAIL_USERNAME: your_email@example.com # Placeholder
      EMAIL_PASSWORD: your_email_password # Placeholder
      EMAIL_SERVER: smtp.example.com # Placeholder
      EMAIL_PORT: 587 # Placeholder
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"

volumes:
  postgres_data:
  grafana_data:
