version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploaded_files:/app/uploaded_files
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/insight_miner
      REDIS_URL: redis://redis:6379/0
      GOOGLE_APPLICATION_CREDENTIALS: /app/google-credentials.json # Placeholder
      AWS_ACCESS_KEY_ID: your_aws_access_key_id # Placeholder
      AWS_SECRET_ACCESS_KEY: your_aws_secret_access_key # Placeholder
      AWS_REGION_NAME: us-east-1 # Placeholder

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: insight_miner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./backend/uploaded_files:/app/uploaded_files
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/insight_miner
      REDIS_URL: redis://redis:6379/0

volumes:
  postgres_data: