apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: insight-miner-backend:latest # Re-use backend image
        command: ["celery", "-A", "celery_worker.celery_app", "worker", "--loglevel=info"]
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@db-service:5432/insight_miner
        - name: REDIS_URL
          value: redis://redis-service:6379/0
        - name: EMAIL_USERNAME
          value: your_email@example.com # Mount as secret
        - name: EMAIL_PASSWORD
          value: your_email_password # Mount as secret
        - name: EMAIL_SERVER
          value: smtp.example.com
        - name: EMAIL_PORT
          value: "587"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
